# Generated by Django 2.0rc1 on 2018-01-12 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban', models.CharField(max_length=40)),
                ('bic', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=256)),
                ('status_client', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=256)),
                ('status_company', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_date', models.DateTimeField(verbose_name='date movement')),
                ('expiration_date', models.DateTimeField(verbose_name='expiration date')),
                ('text', models.CharField(max_length=256)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.BankAccount')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('question_explanation', models.CharField(default='texto', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='TypeofPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(max_length=256)),
                ('pub_date', models.DateTimeField(verbose_name='date added')),
                ('type', models.CharField(max_length=24)),
            ],
        ),
        migrations.AddField(
            model_name='movement',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.TypeofPayment'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.Question'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.CompanyGroup'),
        ),
    ]
