# Generated by Django 2.0rc1 on 2018-02-02 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typeofpayment',
            old_name='types',
            new_name='type',
        ),
    ]
