# Generated by Django 2.0rc1 on 2018-01-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='currency',
            field=models.CharField(choices=[('E', 'EUROS'), ('D', 'DOLARES'), ('L', 'LIBRAS')], max_length=1),
        ),
    ]
