# Generated by Django 2.0rc1 on 2018-01-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20180112_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='estimacion',
            field=models.CharField(choices=[('C', 'Confirmado'), ('P', 'Previsto')], default='P1', max_length=1),
        ),
    ]
