# Generated by Django 2.0rc1 on 2018-01-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_movement_estimacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='estimacion',
            field=models.CharField(choices=[('C', 'Confirmado'), ('P', 'Previsto'), ('-', 'Abierto')], default='-', max_length=1),
        ),
    ]
