# Generated by Django 2.0rc1 on 2018-01-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_auto_20180126_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeofpayment',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
