# Generated by Django 2.0rc1 on 2018-01-30 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_typeofpayment_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typeofpayment',
            old_name='priority',
            new_name='prioridad',
        ),
    ]
