# Generated by Django 2.0rc1 on 2018-01-30 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_auto_20180130_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
